### ISSUE TITLE
the destination ethernet address can be outside my network? 

### ISSUE THREAD

**Issue by danieagle** [mdlayher/ethernet#5]
The data will arrive in destiny address same if this address non reside in my local ethernet segment? 
Very Very Very thanks in Advance, 
Dani.

**Comment by mdlayher** [comment]
If I understand what you're asking: Ethernet by definition only travels along the local Ethernet segment, as that is where the source/destination MAC addresses must live. To make it travel elsewhere, you'd need a higher layer protocol like IP, or maybe you could write some sort of proxy thing. But this question is far too general and would also be OS-specific I assume.

Since this isn't an issue with this package, closing.
